---
apiVersion: v1
kind: Secret
metadata:
  name: exapg-postgres-secret
  namespace: exapg
  labels:
    app.kubernetes.io/name: exapg
    app.kubernetes.io/component: database-secret
type: Opaque
data:
  # PostgreSQL user credentials (base64 encoded)
  # Default: postgres / exapg_secure_password_123
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: ZXhhcGdfc2VjdXJlX3Bhc3N3b3JkXzEyMw==
  POSTGRES_DB: ZXhhZGI=
  
  # Replication user
  POSTGRES_REPLICATION_USER: cmVwbGljYXRvcg==
  POSTGRES_REPLICATION_PASSWORD: cmVwbF9zZWN1cmVfcGFzc3dvcmRfNDU2

---
apiVersion: v1
kind: Secret
metadata:
  name: exapg-ssl-secret
  namespace: exapg
  labels:
    app.kubernetes.io/name: exapg
    app.kubernetes.io/component: ssl-secret
type: kubernetes.io/tls
data:
  # SSL/TLS certificates (base64 encoded)
  # These would be replaced with real certificates in production
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNLVENDQVpJQ0NRRFFHMWJhbFFZbHBUQU5C
    Z2txaGtpRzl3MEJBUXNGQURBYk1Sa3dGd1lEVlFRRERCQmwKZUdGd1p5MWpiMjV6YVhSbGJtTmxk
    bUpoY2pBZUZ3MHlOREExTWpjeE1qTTJNVEJhRncweU5UQTFNamN4TWpNMgpNVEJhTUJzeEdUQVhC
    Z05WQkFNTUVHVjRZWEJuTFdOdmJuTnBkR1Z1WTJWMGRtSmhjakNDQVNJd0RRWUpLb1pJCmh2Y05B
    UUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTEYrd2ZaZ1M4VmxaVGM1cGFkOVdxNzk5SmpYVUZLK3Yr
    M0EKN1ZhN21xM0tUcU9QOVlmSnhwVk5JRUFhdUFMdUJJdEtWZzNXRVNQbXgxM1dtTG01cE1xRk9w
    NkNOQmYzT2VLcQpDeWZpaWhJb21rOXB4dTBWZHJkVWowNnl0V1F2c1JIOVBiV3FsN0F5Vzh6bTMx
    cFJLTlE4Q2pzRGw5SmJXNTJpCkFOcG5mOW5DM0xOZz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0t
    LQ==
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktnd2dnU2tBZ0VBQW9JQkFRQ3hmOEgyWUV2RlpXVTMKT2FXbmZWcXUvZlNZMTFCU3Z1dnR3
    TzFXdTVxdHlrNmpqL1dIeWNhVlRTQkFHcmdDN2dTTFNsWU4xaEVqNXNkZAoxcGk1dWFUS2hUcWVn
    alFYOXpuaXFnc240b29TS0pwUGFjYnRGWGEzVkk5T3NyVmtMN0VSL1QyMXFwZXdNbHZNCjV0OWFV
    U2pVUEFvN0E1ZlNXMXVkb2dEYVozL1p3dHl6WS5BZ01CQUFFQ2dnRUJBSVdTTkV4ZTU0UFlYTy9P
    CkFqK09KQzA1OHJPdWZXUk5RWHZTeFZkVDVrZUhOaUhnNVhNVXVKM0JNMnEKLS0tLS1FTkQgUFJJ
    VkFURSBLRVktLS0tLQ==
  ca.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNIVENDQVlZQ0NRRDFsV0xMV1lBOFVUQU5C
    Z2txaGtpRzl3MEJBUXNGQURBUk1ROHdEUVlEVlFRRERBWmwKZUdGd1p6QWVGdzB5TkRBMU1qY3hN
    ak0yTURoYUZ3MHlOVEExTWpjeE1qTTJNRGhhTUJFeER6QU5CZ05WQkFNTQpCbVY0WVhCbk1JSUJp
    akFOQmdrcWhraUc5dzBCQVFFRkFBT0NBWThBTUlJQmlnS0NBWUVBcHJGdW90TXNXdkVOCnBSaUhB
    WnZQM2dyRGFyL0JPcXBad1J3blhEQ09jemNhTzJaQ2E2dmZZQTlLRFEvWW8zQ0dxcUhVclEzVUpr
    VFoKY3VoTjlWWnVJSU1zSTlpZXdZelR6L3dpVDU5d3NlSkZWZk02dVdGVjFKVVBZaXczTXFtcDlt
    SGJPMkFjb3Z2SQpPUGVxSGpEc2s2dmxQdFV4cVppdTNzNFE9Ci0tLS0tRU5EIENFUlRJRklDQVRF
    LS0tLS0=

---
apiVersion: v1
kind: Secret
metadata:
  name: exapg-monitoring-secret
  namespace: exapg
  labels:
    app.kubernetes.io/name: exapg
    app.kubernetes.io/component: monitoring-secret
type: Opaque
data:
  # Grafana admin credentials (base64 encoded)
  # Default: admin / exapg_grafana_admin_123
  GRAFANA_ADMIN_USER: YWRtaW4=
  GRAFANA_ADMIN_PASSWORD: ZXhhcGdfZ3JhZmFuYV9hZG1pbl8xMjM=
  GRAFANA_SECRET_KEY: U1cyWWN3VEliOXpwT09ob1BzTW0=
  
  # Alertmanager SMTP credentials (if using email alerts)
  ALERT_SMTP_USER: YWxlcnRzQGV4YXBnLmxvY2Fs
  ALERT_SMTP_PASSWORD: Y2hhbmdlbWU=
  
  # Slack webhook URL (if using Slack alerts)
  SLACK_WEBHOOK_URL: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAwMDAwMDAwL0IwMDAwMDAwMC9YWFhYWFhYWFhYWFhYWFhYWFhYWFhY

---
apiVersion: v1
kind: Secret
metadata:
  name: exapg-backup-secret
  namespace: exapg
  labels:
    app.kubernetes.io/name: exapg
    app.kubernetes.io/component: backup-secret
type: Opaque
data:
  # pgBackRest configuration (base64 encoded)
  # AWS S3 credentials for remote backup storage
  AWS_ACCESS_KEY_ID: QUtJQUlPU0ZJTU03RVhBTVBMRQ==
  AWS_SECRET_ACCESS_KEY: d0phbFJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==
  AWS_DEFAULT_REGION: dXMtd2VzdC0y
  
  # Backup encryption key
  BACKUP_ENCRYPTION_KEY: YmFja3VwX2VuY3J5cHRpb25fa2V5XzQ1Ng==
  
  # SMTP credentials for backup notifications
  BACKUP_SMTP_USERNAME: YmFja3VwQGV4YXBnLmxvY2Fs
  BACKUP_SMTP_PASSWORD: YmFja3VwX3Bhc3N3b3JkXzc4OQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: exapg-mgmt-secret
  namespace: exapg
  labels:
    app.kubernetes.io/name: exapg
    app.kubernetes.io/component: management-secret
type: Opaque
data:
  # Management UI session secret
  SECRET_KEY: ZXhhcGctc2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
  
  # pgAdmin credentials (base64 encoded)
  # Default: admin@exapg.local / admin123
  PGADMIN_EMAIL: YWRtaW5AZXhhcGcubG9jYWw=
  PGADMIN_PASSWORD: YWRtaW4xMjM= 